### ISSUE TITLE
rbenv 1.0 ship checklist

### ISSUE THREAD

**Issue by mislav** [rbenv/rbenv#808]
This is a 🚢 checklist for rbenv 1.0 release, combining items from the [v1.0 milestone](https://github.com/sstephenson/rbenv/milestones/1.0) together with some extra notes.

- [x] Expose `version-name` and `version-origin` hooks #739 - *needs decision*
- [x] <del>`rbenv update` feature #301</del>
- [x] Confusing behavior in `rbenv local` #807 - *now would be the time to correct this!*
- Checks that will be covered by [the rbenv-doctor script](https://github.com/rbenv/rbenv-installer/blob/master/bin/rbenv-doctor):
  - [x] Alert users if ruby-build isn't installed. #738
  - [x] Installing gems with --user-install binpath #554
  - [x] Mention in docs not to use sudo when installing gems? #532
  - [x] Checks rbenv installed and configured correctly feature #377
- [x] Move rbenv, ruby-build, and non-obsolete official plugins to the "rbenv" org on GitHub
  - [x] <del>Create rbenv-plugins organization to track maintainer approved plugins. #332</del>
  - [x] Ensure current contributors to ruby-build & plugins have write access to those repos
- [x] Make installer script that performs `make -C src`; incorporate into Homebrew formula
- [x] <del>Revise documentation for installer & doctor scripts</de> <ins>(will finalize after the release, since it's in a separate repo</ins>
- [x] Finalize release notes
- [x] Tag and 🚀❗https://github.com/rbenv/rbenv/issues/837

**Comment by mislav** [comment]
rbenv 1.0 is :ship:

**Comment by hsbt** [comment]
:gem: :ribbon:
